spring:
  application:
    name: fundoscope-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/thunder_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Ensures Hibernate updates schema automatically
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true  # Enable Flyway for database migrations
    locations: classpath:Database  # Point to the Database folder for migration scripts
    baseline-on-migrate: true  # If the schema is empty or not yet initialized, Flyway will apply the migrations
    sql-migration-prefix: V  # Prefix for the migration scripts (e.g., V1__create_table.sql, V2__add_column.sql)
    sql-migration-separator: "__"  # Separator between version and description in migration file names (default: __)
    placeholder-replacement: true  # Enables the use of placeholders in SQL scripts

  sql:
    init:
      schema-locations: classpath:Database/*.sql  # Reads all SQL files in the Database folder

  security:
    jwt:
      secret-key: "s8#Gv2!kLz@rNp$QyW1^dTx3&VoUbKmC"  # Secure this in production
      expiration: 86400000  # 24 hours in milliseconds (24 * 60 * 60 * 1000)
