spring:
  application:
    name: thunderscope-scalable-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/thunder_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always
      schema-locations: classpath:/Database/*.sql

  security:
    jwt:
      secret-key: "s8#Gv2!kLz@rNp$QyW1^dTx3&VoUbKmC"  #  Secure this in production
      expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        jdbc:
          core: DEBUG

